[supervisord]
nodaemon=true

[program:bot1]
command=python main.py
autostart=true
autorestart=true

# [program:bot2]
# command=python logs.py
# autostart=true
# autorestart=true

[program:bot3]
command=python jday.py
autostart=true
autorestart=true

[program:bot4]
command=python AI.py
autostart=true
autorestart=true